version: '3.8'
services:
  webapp:
    build: 
      context: .
      dockerfile: ./Gotorz/Gotorz/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - database
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=GotorzDB;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y  
      - SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"